# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param synth.incrementalSynthesisCache C:/Users/huang/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-2216-DESKTOP-OQNQAOP/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.cache/wt [current_project]
set_property parent.project_path C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {{C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.srcs/sources_1/imports/Single Cycle MIPS Source_Initial/memfile.dat}}
read_verilog -library xil_defaultlib {
  {C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.srcs/sources_1/imports/Single Cycle MIPS Source_Initial/controlunit.v}
  {C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.srcs/sources_1/imports/Single Cycle MIPS Source_Initial/cu_parts.v}
  {C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.srcs/sources_1/imports/Single Cycle MIPS Source_Initial/datapath.v}
  {C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.srcs/sources_1/imports/Single Cycle MIPS Source_Initial/dp_parts.v}
  {C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.srcs/sources_1/imports/Single Cycle MIPS Source_Initial/mem_parts.v}
  {C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.srcs/sources_1/imports/Single Cycle MIPS Source_Initial/mips.v}
  {C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.srcs/sources_1/imports/Single Cycle MIPS Validation_F17/utility.v}
  {C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.srcs/sources_1/imports/Single Cycle MIPS Validation_F17/mips_fpga.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.srcs/constrs_1/imports/Single Cycle MIPS Validation_F17/mips_fpga.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/huang/Documents/School/CMPE140/Lab6/Lab6.srcs/constrs_1/imports/Single Cycle MIPS Validation_F17/mips_fpga.xdc}}]


synth_design -top mips_fpga -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mips_fpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mips_fpga_utilization_synth.rpt -pb mips_fpga_utilization_synth.pb"
